CXX = clang++

LDLIBS = -lm -lstdc++
CXXFLAGS = -MD -O0 -ggdb -std=c++11
LDFLAGS =

all: icepll

icepll: icepll.o
	$(CXX) -o $@ $(LDFLAGS) $^ $(LDLIBS)

clean:
	rm -f icepll
	rm -f *.o *.d

.PHONY: all clean
