CC=gcc

LIB=../../../../build-data/linux_x86_64/lib
LDLIBS = -lftdi1 -lusb-1.0 -lm -lpthread
LDFLAGS = -static -L $(LIB)
CFLAGS = -MD -O0 -Wall -std=c99

all: iceprog

iceprog: iceprog.o

clean:
	rm -f iceprog
	rm -f *.o *.d

.PHONY: all clean
