sudo: required
dist: trusty

language: cpp

matrix:
  include:
    - os: linux
      env: TARGET=windows_x86

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:tes/ams; fi
  - if [[ "$TARGET" == "linux_i686" || "$TARGET" == "windows_x86" ]]; then sudo dpkg --add-architecture i386; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -y -qq; fi

script:
  - bash build.sh $TARGET

deploy:
  provider: releases
  api_key:
    secure: JiEowTxwatI0rl9erGm+tUxwd1uXcdyOMLzloQDMboIVDvwsZAlGV+GrA+1aOZvGF3dEIDCUCeZHf1UbRGo22uKL1UXIrc9mBMklEqekQSrhQeXmF8jsF6TRMEVn0POeQPWYMx5NWcyZOcwQcmifm10dn4lLcRx1H7IRa8Q4EPo88rgG3ukhGfytK2XUfx3mcry5HNIQ6X05LkEHGpR6Tz4kVlLTIskY0dqbrQ7cerWJx8VXfEdhyHlj8ms4UTsAzPD1E40cwPbmt++DvwYCaE7/XtjO2PsWfAUaQxaJwamAWrgbWqCBKnOdHA/IZkXA0jW4VJxwQRUE3WGQ5Ocvdr18NueJn7D8ynSI8qZIGVhxLPIPQujkt/3XBLTeNVddMh2UppTIfrB+cOGrcFpG73h9HJs3jttYYJHKX/EvZO+BIQcbOm80NpkzVXT0USreTF5D8/kCj8v8pA++uOVEEP+rjaFeDu8q+qO09r0DkR8YQwn8scuScXNkSpN+RQ90dTiVZRIU111AS5LHZnPpXVVCi88xLPlsgtZTnay0Rt5eRZYjrpnglNzW/M0rDeCbBbhDp7dmEoFPnFo2WRyuNWoiWPU6X9jwUDV/vBYycHaBr7wPEoVpNolelrYVsE16ge8fNB1iVXdjGx/wDustJTHKck7KBgE8bIq8rNhpmIo=
  file:
    - _packages/**/*.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    all_branches: true
