CXX = i686-w64-mingw32-g++

LDLIBS = -lm -lstdc++
CXXFLAGS = -MD -O0 -ggdb -std=c++11
LDFLAGS = -static

all: icebram.exe

icebram.exe: icebram.o
	$(CXX) -o $@ $(LDFLAGS) $^ $(LDLIBS)

clean:
	rm -f icebram.exe
	rm -f *.o *.d

.PHONY: all clean
