CXX = clang++

LDLIBS = -lm -lstdc++
CXXFLAGS = -MD -O0 -ggdb -std=c++11
LDFLAGS =

all: icebram

icebram: icebram.o
	$(CXX) -o $@ $(LDFLAGS) $^ $(LDLIBS)

clean:
	rm -f icebram
	rm -f *.o *.d

.PHONY: all clean
