CXX = clang++
LDLIBS = -lm -lstdc++
CXXFLAGS = -MD -O0 -ggdb -std=c++11
LDFLAGS =

all: icepack

icepack: icepack.o
	$(CXX) -o $@ $(LDFLAGS) $^ $(LDLIBS)

clean:
	rm -f icepack
	rm -f *.o *.d

.PHONY: all clean
