CC = gcc -m32

PREFIX = ../../../../build-data/linux_i686
LDLIBS = -lftdi1 -lusb-1.0 -lm -lpthread
LDFLAGS = -static -L $(PREFIX)/lib -L /usr/lib/i386-linux-gnu
CFLAGS = -MD -O0 -Wall -std=c99

all: iceprog

iceprog: iceprog.o

clean:
	rm -f iceprog
	rm -f *.o *.d

.PHONY: all clean
