CC=gcc -m32
LDLIBS = -lftdi -lusb
LDFLAGS = -static -L /usr/lib/i386-linux-gnu
CFLAGS = -MD -O0 -Wall -std=c99

all: iceprog

iceprog: iceprog.o

clean:
	rm -f iceprog
	rm -f *.o *.d

.PHONY: all clean
