CC=arm-linux-gnueabihf-gcc

PREFIX = ../../build-data/armhf
LDLIBS = -lftdi1 -lusb-1.0 -lm -lpthread
LDFLAGS =  -L $(PREFIX)/lib
CFLAGS = -MD -O0 -Wall -std=c99

all: iceprog

iceprog: iceprog.o

clean:
	rm -f iceprog
	rm -f *.o *.d

.PHONY: all clean
