CC=arm-linux-gnueabihf-gcc
LDLIBS = -lftdi -lusb
LDFLAGS = -static -L /usr/lib
CFLAGS = -MD -O0 -Wall -std=c99

all: iceprog

iceprog: iceprog.o

clean:
	rm -f iceprog
	rm -f *.o *.d

.PHONY: all clean
