CXX = i686-w64-mingw32-g++

LDLIBS = -lm -lstdc++
CXXFLAGS = -MD -O0 -ggdb -std=c++11 -DPREFIX="\"~/.apio/packages/toolchain-icestorm\""
LDFLAGS = -static

all: icetime.exe

icetime.exe: icetime.o
	$(CXX) -o $@ $(LDFLAGS) $^ $(LDLIBS)

icetime.o: icetime.cc timings.inc

timings.inc: timings.py ../icefuzz/timings_*.txt
	python3 timings.py > timings.inc.new
	mv timings.inc.new timings.inc

clean:
	rm -f icetime.exe timings.inc
	rm -f *.o *.d

.PHONY: all clean
