CC = aarch64-linux-gnu-gcc

PREFIX = ../../../../build-data/linux_aarch64
LDLIBS = -lftdi1 -lusb-1.0 -lm -lpthread
LDFLAGS = -static -L $(PREFIX)/lib
CFLAGS = -MD -O0 -Wall -std=c99

all: iceprog

iceprog: iceprog.o

clean:
	rm -f iceprog
	rm -f *.o *.d

.PHONY: all clean
