CC = i686-w64-mingw32-gcc

LDLIBS =  -lftdi1 -lm -lusb-1.0
LDFLAGS = -static -L ~/.windows_i386/lib
CFLAGS = -MD -O0 -Wall -std=c99 -I ~/.windows_i386/include/libftdi1

all: iceprog.exe

iceprog.exe: iceprog.o
	$(CC) -o $@ $(LDFLAGS) $^ $(LDLIBS)

clean:
	rm -f iceprog.exe
	rm -f *.o *.d

-include *.d

.PHONY: all clean
