CXX = i686-w64-mingw32-g++
LDLIBS = -lm -lstdc++
CXXFLAGS = -MD -O0 -ggdb -std=c++11
LDFLAGS = -static

all: icepack.exe

icepack.exe: icepack.o
	$(CXX) -o $@ $(LDFLAGS) $^ $(LDLIBS)

clean:
	rm -f icepack
	rm -f *.o *.d

.PHONY: all clean
