CXX = arm-linux-gnueabihf-gcc
CC = arm-linux-gnueabihf-g++
LDLIBS = -lm -lstdc++
CXXFLAGS = -MD -O0 -ggdb -std=c++11
LDFLAGS = -static

all: icepack

icepack: icepack.o
	$(CC) -o $@ $(LDFLAGS) $^ $(LDLIBS)

clean:
	rm -f icepack
	rm -f *.o *.d

.PHONY: all clean
